spring:
  cloud:
    gateway:
      routes:
        - id: test_routte
          uri: https://www.baidu.com/
          predicates:
            - Query=url,baidu
        - id: qq_routte
          uri: https://www.qq.com/
          predicates:
            - Query=url,qq
        - id:  cdn_test
          uri:  https://blog.csdn.net/
          predicates:
            - Query=url,cdn
